language: python
matrix:
  include:
    - os: linux
      sudo: required
      dist: xenial
      python: 3.7
      env: PYTHON="python3" PACKAGES="python3-setuptools python3-pep8 python3-pyflakes python3-gi python3-gi-cairo libpython3-dev libjpeg-dev gir1.2-rsvg-2.0" SHOEBOT_GI="pgi"

install:
 - if [ "$PYTHON" == "pypy" ]; then sudo add-apt-repository -y ppa:pypy/ppa; fi
 - sudo apt-get update -q
 - sudo apt-get install --no-install-recommends -y xvfb gir1.2-gtk-3.0 gobject-introspection libcairo2-dev libglib2.0-dev libgirepository1.0-dev build-essential libcairo2-dbg libglib2.0-0-dbg $(echo $PACKAGES)
 - sudo ./install/install_dependencies.sh
 - pip install vext.gi
 - pip install setuptools>=18.8 pycairo>=1.18.1 meta==1.0.2 Pillow>=6.0.0 pubsub==0.1.2
 - pip install --no-deps .
 - pip freeze

script:
 - $PYTHON setup.py test
 - $PYTHON setup.py diagnose
